spring:
  application:
    name: auth-service

  data:
    redis:
      host: redis
      port: 6379
      password: password

  datasource:
    url: jdbc:postgresql://postgres:5432/vote_app_auth_db
    username: postgres
    password: postgres

  kafka:
    bootstrap-servers: kafka:9092

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  cloud:
    discovery:
      enabled: true

app:
  tempPasswordExpiration: 10m
  jwt:
    secret: 7f5d8c4b3a9e1f2a6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8g9h0
    tokenExpiration: 30m
    refreshTokenExpiration: 30d

  kafka:
    kafkaEventTopic: user-registration-event-topic
    kafkaValidateEventTopic: user-online-time-event-topic
    kafkaAccountRegistrationEventTopic: account-events-topic
    kafkaEventGroupId: user-registration-event-group-id

  salt: "SuperSecretSalt"

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/

#server:
#  port: 8081
#sonar:
#  jacoco:
#    reportPaths: target/site/jacoco/jacoco.xml