spring:
  application:
    name: users-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/vote_app_user_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: kafka:9092

app:
  kafka:
    kafkaEventTopic: user-registration-event-topic
#    kafkaAccountRegistrationEventTopic: account-events-topic
    kafkaEventGroupId: user-registration-event-group-id

external-api:
  authServiceUrl: "gateway:8080/api/v1/auth"

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/