spring:
  application:
    name: voting-service

  data:
    mongodb:
      uri: mongodb://mongodb:27017/voting-db

  kafka:
    bootstrap-servers: kafka:9092

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

app:
  kafka:
    notificationEventTopic: notification-to-community-send-event-topic
    notificationEventGroupId: notification-send-event-group-id
    communityModerationEventTopic: community-moderation-event-topic
    membershipEventTopic: membership-event-topic

external-api:
  authServiceUrl: "gateway:8080/api/v1/auth"

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/