spring:
  application:
    name: voting-service

  data:
    mongodb:
      uri: mongodb://mongodb:27017/voting-db

  kafka:
    bootstrap-servers: kafka:9092

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

app:
  kafka:
    kafkaEventTopic: community-save-event-topic
    kafkaEventDeleteTopic: community-delete-event-topic
    #    kafkaAccountRegistrationEventTopic: account-events-topic
    kafkaEventGroupId: community-save-event-group-id

external-api:
  authServiceUrl: "gateway:8080/api/v1/auth"

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/