spring:
  application:
    name: membership-service

  datasource:
    url: jdbc:postgresql://postgres:5432/vote_app_user_community_ship_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  r2dbc:
    url: r2dbc:postgresql://postgres:5432/vote_app_user_community_ship_db
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: kafka:9092

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

app:
  kafka:
    kafkaEventTopic: community-save-event-topic
    #    kafkaAccountRegistrationEventTopic: account-events-topic
    kafkaEventGroupId: community-save-event-group-id

external-api:
  authServiceUrl: "gateway:8080/api/v1/auth"

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/