spring:
  application:
    name: community-service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/vote_app_community_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: kafka:9092

app:
  kafka:
    kafkaEventTopic: community-save-event-topic
    #    kafkaAccountRegistrationEventTopic: account-events-topic
    kafkaEventGroupId: community-save-event-group-id

external-api:
  authServiceUrl: "194.67.88.81:8080/api/v1/auth"

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/

