version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7.0.12
    container_name: redis
    command: [ "redis-server", "--requirepass", "password" ]
    ports:
      - "6379:6379"
