spring:
  application:
    name: geo-storage-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/vote_app_geo_storage_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  data:
    redis:
      host: redis
      port: 6379
      timeout: 60000
      password: password

external-api:
  hhUrl: "https://api.hh.ru/areas"
  authServiceUrl: "gateway:8080/api/v1/auth"

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  bucket-name: app-vote.images
  baseUrl: "https://storage.yandexcloud.net/"
  folder: "folder/"
